### ISSUE TITLE
Add Viral Load Field on NewOrEditPatientScreen

### ISSUE THREAD

**Issue by chrisly-bear** [chrisly-bear/PEBRApp#1]
The user should be able to input the viral load of a patient when he creates/edits a patient. Selectable options should be:
- suppressed
- unsuppressed
- N/A

**Comment by ntoane** [comment]
Added the Viral Load Selection field with three options; Suppressed, Unsuppressed and N/A. On patient registration, any of the selected option will be recorded in DB. However, on edit characteristics, the new selected option is not recorded, if I use the instance of Patient in _NewOrEditPatientFormState class the variable _vlSuppressed is declared private and therefore cannot be accessed like other variables, will look onto it adding get and set functions to access the variable.

Also on patient registration I changed the field for district from typing a district to selecting from list of district. If this is OK we can approve

**Comment by chrisly-bear** [comment]
Thank you for your contribution @ntoane! Just a few remarks:

1. Please do not push to the `develop` branch. Instead, create a new feature branch with the name `{github-issue-number}-{github-issue-name}` and push all your changes to the feature branch. When your work on this feature (issue) is done, create a merge request to merge the feature branch into the `develop` branch. I moved your commits to the feature branch `1-add-viral-load-field`. Please commit any further changes related to this issue to that branch.
2. In the `lib/database/models/Patient.dart` file, some newer changes of the `develop` branch got reversed by your second commit. This probably happened because you weren't on the newest version of the `develop` branch when committing your changes. I reversed those changes in the `1-add-viral-load field` branch so there's no further action required on your part.

**Comment by chrisly-bear** [comment]
Requirements changed. Will be implemented as part of #23.
